
name: 'Terraform CI/CD'

on:
  push:
    branches:
      - main
      - test
      - dev
  pull_request:

jobs:
  terraform:
    name: 'Deploy Terraform to Azure'
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
    - uses: actions/checkout@v3
    
    - name: 'Set up Azure credentials'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: 'Print github.ref'
      run: echo ${GITHUB_REF##*/} 

    - name: 'Setup Terraform'
      uses: hashicorp/setup-terraform@v1

    - name: 'Set up Azure credentials'
      run: |
        echo "ARM_CLIENT_ID=${{ secrets.AZURE_CLIENT_ID }}" >> $GITHUB_ENV
        echo "ARM_CLIENT_SECRET=${{ secrets.AZURE_CLIENT_SECRET }}" >> $GITHUB_ENV
        echo "ARM_SUBSCRIPTION_ID=${{ secrets.AZURE_SUBSCRIPTION_ID }}" >> $GITHUB_ENV
        echo "ARM_TENANT_ID=${{ secrets.AZURE_TENANT_ID }}" >> $GITHUB_ENV

    - name: 'Terraform Init'
      run: terraform init -backend-config=key=${{ github.ref == 'refs/heads/main' && 'prod' || (github.ref == 'refs/heads/test' && 'test' || 'dev') }}-terraform.tfstate

    - name: 'Terraform Validate'
      run: terraform validate

    - name: 'Terraform Plan'
      run: terraform plan -var-file=./${{ github.ref == 'refs/heads/main' && 'prod' || (github.ref == 'refs/heads/test' && 'test' || 'dev') }}.tfvars


    - name: 'Terraform Apply'
      if: github.event_name == 'push' && (github.ref == 'refs/heads/test' || github.ref == 'refs/heads/main')
      run: terraform apply -var-file="${{ github.ref == 'refs/heads/main' && './prod.tfvars' || './test.tfvars' }}" -auto-approve
      env:
        ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
        ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
